### ISSUE TITLE
ID элементов

### ISSUE THREAD

**Issue by miraage** [kafeman/HabraStorage-HTML5-uploader#1]
Если загрузить много файлов, то будет путаница с id элементов (будет много file-name-0).

Как вариант - хранить где-нибудь текущее кол-во файлов, и инкрементировать после каждой итерации.

**Comment by kafeman** [comment]
Нет, дело явно не в этом. "file-name-" можно было вообще не писать, но я на всякий случай скопировал как у Хабра.

Там я написал комментарий, что дело в том, что XHR не хочет отправлять данные повторно. А если создавать каждый раз новый, то там все-равно возникали глюки когда одна картинка дублировалась 4 раза.

**Comment by miraage** [comment]
Понятно. Я подумал, что могут возникнуть глюки с `this.select()` у элементов.

**Comment by kafeman** [comment]
Еще этот GreaseMonkey отлаживать невозможно - вижу, что на повторной отправке все ломается, а почему - не знаю :-(

**Comment by miraage** [comment]
Если найду багу до ее фикса - оформлю пулл реквест :)
